kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bvcni
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bvcni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bvcni
subjects:
  - kind: ServiceAccount
    name: bvcni
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bvcni
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bvcnid
  namespace: kube-system
  labels:
    app: bvcnid
spec:
  selector:
    matchLabels:
      app: bvcnid
  template:
    metadata:
      labels:
        app: bvcnid
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      hostNetwork: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
      serviceAccountName: bvcni
      containers:
        - name: bvcnid
          image: royroyee/bvcnid:1.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: false
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: cni-bin-dir
              mountPath: /host/opt/cni/bin
            - name: cni-conf
              mountPath: /etc/cni/net.d
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-conf
          hostPath:
            path: /etc/cni/net.d